# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
# Initialize the WebDriver
driver = webdriver.Chrome()  # Ensure chromedriver is in PATH
driver.maximize_window()


def test_lab4EthanTeigan(self):
  driver.get("https://www.calculator.net/body-fat-calculator.html")
  driver.set_window_size(550, 691)
  driver.find_element(By.CSS_SELECTOR, ".cbcontainer:nth-child(2)").click()
  driver.find_element(By.NAME, "cage").send_keys("40")
  driver.find_element(By.NAME, "cweightkgs").send_keys("100")
  driver.find_element(By.ID, "cheightmeter").send_keys("189")
  driver.find_element(By.ID, "cneckmeter").send_keys("57")
  driver.find_element(By.ID, "cwaistmeter").send_keys("98")
  driver.find_element(By.ID, "chipmeter").send_keys("100")
  driver.find_element(By.NAME, "calform").click()
  driver.find_element(By.NAME, "x").click()
  gender = "female"
    
  if gender == "female":
    driver.find_element(By.CSS_SELECTOR, ".cbcontainer:nth-child(2)").click()
    driver.find_element(By.NAME, "cage").send_keys("40")
    driver.find_element(By.NAME, "cweightkgs").send_keys("100")
    driver.find_element(By.ID, "cheightmeter").send_keys("189")
    driver.find_element(By.ID, "cneckmeter").send_keys("57")
    driver.find_element(By.ID, "cwaistmeter").send_keys("98")
    driver.find_element(By.ID, "chipmeter").send_keys("100")
    driver.find_element(By.NAME, "calform").click()
    result_text = driver.find_element(By.XPATH, "//div[@class='rightresult']").text
    assert "Body Fat: 23.0%" in result_text, "Unexpected result for female"
    print("Body Fat Calculation Result:", result_text)
  else:
    driver.find_element(By.CSS_SELECTOR, ".cbcontainer:nth-child(1) > .rbmark").click()
    driver.find_element(By.NAME, "cage").send_keys("15")
    driver.find_element(By.NAME, "cweightkgs").send_keys("220")
    driver.find_element(By.ID, "cheightmeter").send_keys("90")
    driver.find_element(By.ID, "cneckmeter").send_keys("18")
    driver.find_element(By.ID, "cwaistmeter").send_keys("100")
    driver.find_element(By.NAME, "calform").click()
    result_text = driver.find_element(By.XPATH, "//div[@class='rightresult']").text
    assert "Body Fat: 23.0%" in result_text, "Unexpected result for female"
    print("Body Fat Calculation Result:", result_text)
  
