# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

# Initialize the WebDriver
driver = webdriver.Chrome()  # Ensure chromedriver is in PATH
driver.maximize_window()


class BodyFatIndexTest:

  def setup_method(self,method):
    # Initialize the WebDriver
    self.driver = webdriver.Chrome()
  
  def teardown_method(self,method):
     self.driver.quit()

  def test_lab4EthanTeiganFemale(driver):
    driver.get("https://www.calculator.net/body-fat-calculator.html")
    driver.set_window_size(550, 691)
    driver.find_element(By.CSS_SELECTOR, ".cbcontainer:nth-child(2)").click()
    driver.find_element(By.NAME, "cage").send_keys("40")
    driver.find_element(By.NAME, "cweightkgs").send_keys("100")
    driver.find_element(By.ID, "cheightmeter").send_keys("189")
    driver.find_element(By.ID, "cneckmeter").send_keys("57")
    driver.find_element(By.ID, "cwaistmeter").send_keys("98")
    driver.find_element(By.ID, "chipmeter").send_keys("100")
    driver.find_element(By.NAME, "calform").click()
    driver.find_element(By.NAME, "x").click()
    gender = "female"
      
    gender = "female"  # Change to "male" as needed

    if gender == "female":
      driver.find_element(By.XPATH, "//input[@value='f']").click()  # Select female
      driver.find_element(By.NAME, "cage").send_keys("40")
      driver.find_element(By.NAME, "cweightkgs").send_keys("100")
      driver.find_element(By.ID, "cheightmeter").send_keys("189")
      driver.find_element(By.ID, "cneckmeter").send_keys("57")
      driver.find_element(By.ID, "cwaistmeter").send_keys("98")
      driver.find_element(By.ID, "chipmeter").send_keys("100")
      result_text = driver.find_element(By.XPATH, "//div[@class='rightresult']").text
      assert "Body Fat: 23.0%" in result_text, "Unexpected result for female"
      print("Body Fat Calculation Result:", result_text)
      
    else:
      driver.find_element(By.XPATH, "//input[@value='m']").click()  # Select male
      # Add values for male as per task requirements


def test_body_fat_male(self):
        
        # Navigate to Body Fat Calculator
        self.driver.get("https://www.calculator.net/body-fat-calculator.html")

        # Locate the Male radio button
        male_radio = self.driver.find_element(By.ID, "csex1")

        # Use JavaScript to click on the Male radio button
        self.driver.execute_script("arguments[0].click();", male_radio)

        # Continue with the rest of the test steps
        self.driver.find_element(By.NAME, "cage").clear()
        self.driver.find_element(By.NAME, "cage").send_keys("25")
        self.driver.find_element(By.NAME, "cweightkgs").clear()
        self.driver.find_element(By.NAME, "cweightkgs").send_keys("70")
        self.driver.find_element(By.ID, "cheightmeter").clear()
        self.driver.find_element(By.ID, "cheightmeter").send_keys("178")
        self.driver.find_element(By.ID, "cneckmeter").clear()
        self.driver.find_element(By.ID, "cneckmeter").send_keys("50")
        self.driver.find_element(By.ID, "cwaistmeter").clear()
        self.driver.find_element(By.ID, "cwaistmeter").send_keys("96")

        # Calculate and verify the result
        self.driver.find_element(By.NAME, "x").click()
        result_text = self.driver.find_element(By.CSS_SELECTOR, "font > b").text
        assert result_text == "Body Fat: 15.7%"
        print("Male Test Case Result:", result_text)
  